### ISSUE TITLE
mssing igl_stb_image_export.h

### ISSUE THREAD

**Issue by choasma** [libigl/libigl-stb#1]
hello and sorry bother, may I ask where this header file I should include, in order to compile read/write png functionalities in libigl. cheers.
UPDATE: that header file is used in igl_stb_image.h

**Comment by jdumas** [comment]
The file is created by CMake when you generate your project with it, so it should be somewhere in the build folder. If you are using CMake to build your project you shouldn't have to worry about it.

**Comment by choasma** [comment]
Sorry this very dumb question... I just get the file after compiling. Cheers and Merry Christmas!
